name: Plagiarism Checker

on:
  pull_request:
    paths:
      - "games/**/*.js"

jobs:
  split-and-list-files:
    runs-on: ubuntu-latest
    outputs:
      batches: ${{ steps.list-batches.outputs.batches }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Compare50 && beautifulsoup4
        run: pip install compare50 beautifulsoup4

      - name: Get list of changed files
        id: changed-files
        run: |
          echo "Pull Request Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Pull Request Head SHA: ${{ github.event.pull_request.head.sha }}"
          js_files=$(git diff --name-only --diff-filter=AM --find-renames --find-copies ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep 'games/.*\.js$' | xargs)
          echo "FILES=$js_files"
          echo "FILES=$js_files" >> $GITHUB_ENV

      - name: Split files into 10 batches
        run: |
          echo "Running split_into_batches.py"
          python .github/scripts/split_into_batches.py games/ batches/ 10

      - name: List files in batches
        id: list-batches
        run: |
          echo "Listing files in batches"
          batches="[]"
          for dir in batches/*; do
            if [ -d "$dir" ]; then
              echo "Files in $dir:"
              ls "$dir"
              batches=$(jq -c --arg dir "$dir" '. + [$dir]' <<< "$batches")
            fi
          done
          echo "batches=$batches" >> $GITHUB_ENV
          echo "::set-output name=batches::$batches"  # For backward compatibility

  plagiarism-check:
    needs: split-and-list-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: ${{ fromJson(needs.split-and-list-files.outputs.batches) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Compare50 && beautifulsoup4
        run: pip install compare50 beautifulsoup4

      - name: Debug Batch
        run: |
          echo "Processing batch: ${{ matrix.batch }}"

      - name: Run Plagiarism Detection Script
        run: |
          echo "Running plagiarism check for batch: ${{ matrix.batch }}"
          python .github/scripts/plagiarism_check.py "${{ matrix.batch }}" "output_dir" "saved_dir"

  extract-and-upload:
    needs: plagiarism-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Extract and Display Similarity Percentages
        run: |
          echo "Extracting similarity percentages"
          python .github/scripts/extract_percentages.py saved_dir/
        id: extract-percentages

      - name: Upload Compare50 Results as Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compare50-results
          path: saved_dir/

      - name: Save PR number to file
        if: always()
        run: echo ${{ github.event.pull_request.number }} > pr_number.txt

      - name: Upload PR Number as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-number
          path: pr_number.txt

      - name: Upload Plagiarism Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: plagiarism-report
          path: plagiarism-report.md

      - name: Check for High Plagiarism Percentages
        if: always() && steps.extract-percentages.outcome == 'failure'
        run: echo "Plagiarism percentage over threshold detected."