name: Plagiarism Checker

on:
  pull_request_target:
    paths:
      - "games/**/*.js"

permissions: write-all

jobs:
  plagiarism-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Compare50 && beautifulsoup4
        run: pip install compare50 beautifulsoup4

      - name: Get list of changed files
        run: |
          base_sha="${{ github.base_ref }}"
          head_sha="${{ github.sha }}"
          js_files=$(git diff --name-only --diff-filter=AM $base_sha..$head_sha | grep 'games/.*\.js$' | xargs)
          echo "FILES=$js_files" >> $GITHUB_ENV
          echo "Detected JS files: $js_files"

      - name: Run Plagiarism Detection Script
        env:
          FILES: ${{ env.FILES }}
        run: |
          IFS=' ' read -ra FILES_ARRAY <<< "$FILES"
          for FILE in "${FILES_ARRAY[@]}"; do
            echo "Processing file: $FILE"
            python .github/scripts/plagiarism_check.py "$FILE" games output_dir saved_dir
          done
        shell: /usr/bin/bash -e {0}

      - name: Extract and Display Similarity Percentages
        run: python .github/scripts/extract_percentages.py saved_dir/

      - name: Post Plagiarism Results Comment
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('plagiarism_results.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Check for High Plagiarism Percentages
        if: success()
        run: |
          if grep -qE "(\d{2,3})%" plagiarism_results.txt; then
            echo "Plagiarism percentage over threshold detected."
            exit 1
          fi

      - name: Upload Compare50 Results as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compare50-results
          path: saved_dir/