name: Check Plagiarism

on:
  pull_request:
    paths:
      - '**.js'

jobs:
  plagiarism_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install compare50
        run: pip install compare50

      - name: Clone reference repository
        run: git clone https://github.com/hackclub/sprig.git

      - name: Trim JavaScript file and Check Plagiarism
        run: |
          python -c "import re, glob, os, subprocess;\
          patterns = [r'setLegend\(`.*?`\);', r'map\(`.*?`\);', r'bitmap\(`.*?`\);'];\
          if not os.path.exists('temp'): os.makedirs('temp');\
          files = glob.glob('**/*.js', recursive=True);\
          trimmed_files = [];\
          for file_path in files:\
              with open(file_path, 'r') as file: content = file.read();\
              for pattern in patterns: content = re.sub(pattern, '', content, flags=re.DOTALL);\
              temp_file_path = f'temp/trimmed_{os.path.basename(file_path)}';\
              with open(temp_file_path, 'w') as file: file.write(content);\
              trimmed_files.append(temp_file_path);\
          result = subprocess.run(['compare50', *trimmed_files, 'sprig/games/'], capture_output=True, text=True);\
          print(result.stdout);\
          for file_path in trimmed_files: os.remove(file_path);\
          os.rmdir('temp');"