name: Check Plagiarism

on:
  pull_request:
    paths:
      - '**.js'

jobs:
  plagiarism_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install

      - name: Trim JavaScript files
        run: node .github/scripts/trim-js-files.js

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install compare50
        run: pip install compare50

      - name: Clone reference repository
        run: git clone https://github.com/hackclub/sprig.git

      - name: Run compare50
        run: python .github/scripts/run_compare50.py