name: test-game

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'games/**.js'

permissions:
  contents: read
  pull-requests: read

jobs:
  test-game:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.4.0
        with:
          files: |
            games/**.js

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1

      - name: Check Games
        run: deno run --allow-read tests/sprigfuzzy_workflow.js ${{ steps.changed-files.outputs.all_changed_files }}
